-- Generated by scripts/export-seed-sql.ts. Review before loading into a real database.
begin;

insert into businesses (id, name, legal_name, public_phone, website, timezone, status)
values ('business-bayview', 'Bayview HVAC & Plumbing', 'Bayview HVAC & Plumbing', '(510) 555-0142', 'https://bayviewhvacplumbing.example', 'America/Los_Angeles', 'ready')
on conflict (id) do nothing;

insert into users (id, auth_provider_user_id, name, email)
values ('user-jason-owner', 'mock:user-jason-owner', 'Jason', 'jason-owner@example.invalid')
on conflict (id) do nothing;

insert into users (id, auth_provider_user_id, name, email)
values ('user-nina-dispatch', 'mock:user-nina-dispatch', 'Nina', 'nina-dispatch@example.invalid')
on conflict (id) do nothing;

insert into users (id, auth_provider_user_id, name, email)
values ('user-maya-manager', 'mock:user-maya-manager', 'Maya', 'maya-manager@example.invalid')
on conflict (id) do nothing;

insert into users (id, auth_provider_user_id, name, email)
values ('user-diego-tech', 'mock:user-diego-tech', 'Diego', 'diego-tech@example.invalid')
on conflict (id) do nothing;

insert into business_memberships (id, business_id, user_id, role, assigned_technician_id, active)
values ('membership-user-jason-owner', 'business-bayview', 'user-jason-owner', 'owner', null, true)
on conflict (id) do nothing;

insert into business_memberships (id, business_id, user_id, role, assigned_technician_id, active)
values ('membership-user-nina-dispatch', 'business-bayview', 'user-nina-dispatch', 'dispatcher', null, true)
on conflict (id) do nothing;

insert into business_memberships (id, business_id, user_id, role, assigned_technician_id, active)
values ('membership-user-maya-manager', 'business-bayview', 'user-maya-manager', 'manager', null, true)
on conflict (id) do nothing;

insert into business_memberships (id, business_id, user_id, role, assigned_technician_id, active)
values ('membership-user-diego-tech', 'business-bayview', 'user-diego-tech', 'technician', 'diego-r', true)
on conflict (id) do nothing;

insert into customers (id, business_id, name, phone, service_address, membership_status, preferred_channel, sentiment, unresolved)
values ('angela-brooks', 'business-bayview', 'Angela Brooks', '(510) 555-0142', '1284 Birch Lane, Oakland, CA 94606', 'None', 'SMS', 'watch', true)
on conflict (id) do nothing;

insert into customers (id, business_id, name, phone, service_address, membership_status, preferred_channel, sentiment, unresolved)
values ('tom-reilly', 'business-bayview', 'Tom Reilly', '(510) 555-0188', '42 Ocean View Dr, Newark, CA 94560', 'Member', 'Call', 'unhappy', true)
on conflict (id) do nothing;

insert into customers (id, business_id, name, phone, service_address, membership_status, preferred_channel, sentiment, unresolved)
values ('erica-patel', 'business-bayview', 'Erica Patel', '(510) 555-0173', '88 Magnolia Ct, Fremont, CA 94538', 'Member', 'SMS', 'positive', false)
on conflict (id) do nothing;

insert into customers (id, business_id, name, phone, service_address, membership_status, preferred_channel, sentiment, unresolved)
values ('daniel-wu', 'business-bayview', 'Daniel Wu', '(510) 555-0119', '655 Pine Hill Rd, Union City, CA 94587', 'None', 'Call', 'neutral', false)
on conflict (id) do nothing;

insert into customers (id, business_id, name, phone, service_address, membership_status, preferred_channel, sentiment, unresolved)
values ('lily-park', 'business-bayview', 'Lily Park', '(510) 555-0211', '12 Redwood Pl, Fremont, CA 94539', 'VIP', 'SMS', 'positive', false)
on conflict (id) do nothing;

insert into customers (id, business_id, name, phone, service_address, membership_status, preferred_channel, sentiment, unresolved)
values ('carlos-mendez', 'business-bayview', 'Carlos Mendez', '(510) 555-0260', '901 Sycamore St, San Leandro, CA 94577', 'None', 'Call', 'neutral', false)
on conflict (id) do nothing;

insert into repeat_issue_flags (id, business_id, customer_id, repeat_issue_flag, callback_risk_score, customer_frustration_score, unresolved_issue_score)
values ('repeat-angela-brooks', 'business-bayview', 'angela-brooks', true, 82, 61, 88)
on conflict (id) do nothing;

insert into repeat_issue_flags (id, business_id, customer_id, repeat_issue_flag, callback_risk_score, customer_frustration_score, unresolved_issue_score)
values ('repeat-tom-reilly', 'business-bayview', 'tom-reilly', true, 86, 91, 93)
on conflict (id) do nothing;

insert into repeat_issue_flags (id, business_id, customer_id, repeat_issue_flag, callback_risk_score, customer_frustration_score, unresolved_issue_score)
values ('repeat-erica-patel', 'business-bayview', 'erica-patel', false, 12, 6, 0)
on conflict (id) do nothing;

insert into repeat_issue_flags (id, business_id, customer_id, repeat_issue_flag, callback_risk_score, customer_frustration_score, unresolved_issue_score)
values ('repeat-daniel-wu', 'business-bayview', 'daniel-wu', false, 24, 12, 31)
on conflict (id) do nothing;

insert into repeat_issue_flags (id, business_id, customer_id, repeat_issue_flag, callback_risk_score, customer_frustration_score, unresolved_issue_score)
values ('repeat-lily-park', 'business-bayview', 'lily-park', false, 9, 4, 0)
on conflict (id) do nothing;

insert into repeat_issue_flags (id, business_id, customer_id, repeat_issue_flag, callback_risk_score, customer_frustration_score, unresolved_issue_score)
values ('repeat-carlos-mendez', 'business-bayview', 'carlos-mendez', false, 33, 18, 47)
on conflict (id) do nothing;

insert into technicians (id, business_id, name, role, trades, service_areas, status, emergency_eligible, shift, current_job_id)
values ('diego-r', 'business-bayview', 'Diego R.', 'lead technician', array['plumbing', 'hvac'], array['Oakland', 'Hayward', 'Fremont'], 'available', true, '{"start":"7:00 AM","end":"6:00 PM"}'::jsonb, null)
on conflict (id) do nothing;

insert into technicians (id, business_id, name, role, trades, service_areas, status, emergency_eligible, shift, current_job_id)
values ('sam-k', 'business-bayview', 'Sam K.', 'technician', array['roofing', 'plumbing'], array['Fremont', 'San Leandro', 'Oakland'], 'on_job', true, '{"start":"8:00 AM","end":"7:00 PM"}'::jsonb, 'job-lily-drain')
on conflict (id) do nothing;

insert into technicians (id, business_id, name, role, trades, service_areas, status, emergency_eligible, shift, current_job_id)
values ('marcus-l', 'business-bayview', 'Marcus L.', 'technician', array['electrical', 'appliance'], array['Hayward', 'Union City', 'Fremont'], 'off_duty', false, '{"start":"Tomorrow 7:00 AM","end":"Tomorrow 5:00 PM"}'::jsonb, null)
on conflict (id) do nothing;

insert into jobs (id, business_id, customer_id, technician_id, trade, title, service_area, window_label, status, emergency, payment_status)
values ('job-erica-ac', 'business-bayview', 'erica-patel', 'diego-r', 'hvac', 'AC tune-up', 'Fremont', 'Fri 10:00 AM - 12:00 PM', 'scheduled', false, 'deposit_collected')
on conflict (id) do nothing;

insert into jobs (id, business_id, customer_id, technician_id, trade, title, service_area, window_label, status, emergency, payment_status)
values ('job-lily-drain', 'business-bayview', 'lily-park', 'sam-k', 'plumbing', 'Drain cleaning', 'Fremont', 'Today 12:00 PM - 1:15 PM', 'in_progress', false, 'link_sent')
on conflict (id) do nothing;

insert into jobs (id, business_id, customer_id, technician_id, trade, title, service_area, window_label, status, emergency, payment_status)
values ('job-angela-emergency-hold', 'business-bayview', 'angela-brooks', 'diego-r', 'plumbing', 'Burst pipe', 'Oakland', 'Emergency hold', 'held', true, 'pending')
on conflict (id) do nothing;

insert into dispatch_events (id, business_id, customer_id, urgency, issue_summary, service_area, confidence_score, repeat_issue_score, callback_risk_score, frustration_score, unresolved_score)
values ('dispatch-angela-burst-pipe', 'business-bayview', 'angela-brooks', 'Critical', 'Burst pipe under kitchen sink', 'Oakland', 92, 92, 82, 61, 88)
on conflict (id) do nothing;

insert into dispatch_events (id, business_id, customer_id, urgency, issue_summary, service_area, confidence_score, repeat_issue_score, callback_risk_score, frustration_score, unresolved_score)
values ('dispatch-carlos-roof-leak', 'business-bayview', 'carlos-mendez', 'High', 'Active roof leak after storm', 'San Leandro', 47, 0, 33, 18, 47)
on conflict (id) do nothing;

insert into conversations (id, business_id, customer_id, channel, provider, provider_conversation_id, status, urgency, confidence, summary)
values ('conv-angela-voice', 'business-bayview', 'angela-brooks', 'voice', 'mock_voice', 'CA_mock_angela_001', 'escalated', 'critical', 96, 'Emergency intake complete. Shutoff confirmed, photos requested, and dispatch approval is ready.')
on conflict (id) do nothing;

insert into conversations (id, business_id, customer_id, channel, provider, provider_conversation_id, status, urgency, confidence, summary)
values ('conv-erica-voice', 'business-bayview', 'erica-patel', 'voice', 'mock_voice', 'CA_mock_erica_001', 'booked', 'normal', 91, 'Booked Friday 10:00 AM with Diego after availability, travel buffer, and membership preference checks.')
on conflict (id) do nothing;

insert into conversations (id, business_id, customer_id, channel, provider, provider_conversation_id, status, urgency, confidence, summary)
values ('conv-daniel-voice', 'business-bayview', 'daniel-wu', 'voice', 'mock_voice', 'CA_mock_daniel_001', 'follow_up', 'high', 71, 'Possible electrical panel risk. AI avoided diagnosis and routed to dispatcher review.')
on conflict (id) do nothing;

insert into conversations (id, business_id, customer_id, channel, provider, provider_conversation_id, status, urgency, confidence, summary)
values ('conv-carlos-after-hours', 'business-bayview', 'carlos-mendez', 'voice', 'mock_voice', 'CA_mock_carlos_001', 'captured', 'high', 88, 'After-hours roof leak captured and morning tarp window held for dispatcher approval.')
on conflict (id) do nothing;

insert into conversations (id, business_id, customer_id, channel, provider, provider_conversation_id, status, urgency, confidence, summary)
values ('conv-unknown-recovery', 'business-bayview', null, 'sms', 'mock_sms', 'SM_mock_unknown_001', 'missed_recovered', 'low', 42, 'Caller hung up after 3 seconds. Recovery SMS sent and lead remains open.')
on conflict (id) do nothing;

insert into payment_requests (id, business_id, customer_id, job_id, amount_cents, reason, status, provider, provider_payment_id)
values ('payreq-angela-emergency', 'business-bayview', 'angela-brooks', 'job-angela-emergency-hold', 15000, 'emergency_deposit', 'pending', 'stripe_connect', null)
on conflict (id) do nothing;

insert into payment_requests (id, business_id, customer_id, job_id, amount_cents, reason, status, provider, provider_payment_id)
values ('payreq-erica-deposit', 'business-bayview', 'erica-patel', 'job-erica-ac', 5000, 'deposit', 'paid', 'stripe_connect', 'cs_test_erica_deposit')
on conflict (id) do nothing;

insert into payment_requests (id, business_id, customer_id, job_id, amount_cents, reason, status, provider, provider_payment_id)
values ('payreq-lily-diagnostic', 'business-bayview', 'lily-park', 'job-lily-drain', 8900, 'diagnostic_fee', 'requested', 'stripe_connect', null)
on conflict (id) do nothing;

insert into payment_events (id, business_id, payment_request_id, provider_event_id, type, payload)
values ('pe-erica-link', 'business-bayview', 'payreq-erica-deposit', null, 'link_sent', '{"at":"Today 9:19am","detail":"Secure checkout link sent by SMS."}'::jsonb)
on conflict (id) do nothing;

insert into payment_events (id, business_id, payment_request_id, provider_event_id, type, payload)
values ('pe-erica-paid', 'business-bayview', 'payreq-erica-deposit', 'evt_erica_paid', 'paid', '{"at":"Today 9:21am","detail":"$50 deposit collected by Apple Pay."}'::jsonb)
on conflict (id) do nothing;

insert into payment_events (id, business_id, payment_request_id, provider_event_id, type, payload)
values ('pe-erica-confirmed', 'business-bayview', 'payreq-erica-deposit', null, 'job_confirmed', '{"at":"Today 9:21am","detail":"Appointment confirmed after deposit event."}'::jsonb)
on conflict (id) do nothing;

insert into payment_events (id, business_id, payment_request_id, provider_event_id, type, payload)
values ('pe-lily-link', 'business-bayview', 'payreq-lily-diagnostic', null, 'link_sent', '{"at":"8 min ago","detail":"$89 diagnostic fee link sent by SMS."}'::jsonb)
on conflict (id) do nothing;

insert into payment_status_history (id, business_id, payment_request_id, from_status, to_status, actor, note, occurred_at_label)
values ('psh-erica-requested', 'business-bayview', 'payreq-erica-deposit', null, 'requested', 'ai', 'AI sent approved deposit link.', 'Today 9:19am')
on conflict (id) do nothing;

insert into payment_status_history (id, business_id, payment_request_id, from_status, to_status, actor, note, occurred_at_label)
values ('psh-erica-paid', 'business-bayview', 'payreq-erica-deposit', 'requested', 'paid', 'stripe_webhook', 'Checkout session completed.', 'Today 9:21am')
on conflict (id) do nothing;

insert into payment_status_history (id, business_id, payment_request_id, from_status, to_status, actor, note, occurred_at_label)
values ('psh-angela-pending', 'business-bayview', 'payreq-angela-emergency', null, 'pending', 'ai', 'AI held payment request because emergency deposit rule is not owner-confirmed.', 'Held 4 min ago')
on conflict (id) do nothing;

insert into notifications (id, business_id, type, title, body, priority, destination, status)
values ('notif-angela-emergency', 'business-bayview', 'emergency_call', 'Burst pipe emergency', 'Repeat customer. Prior unresolved leak found. Diego is recommended.', 'urgent', '/dispatch', 'sent')
on conflict (id) do nothing;

insert into notifications (id, business_id, type, title, body, priority, destination, status)
values ('notif-lily-payment', 'business-bayview', 'booking_conflict', 'Current job blocks schedule', 'Lily Park is still active. Trowel held the next slot instead of double-booking.', 'important', '/jobs', 'sent')
on conflict (id) do nothing;

insert into notifications (id, business_id, type, title, body, priority, destination, status)
values ('notif-erica-paid', 'business-bayview', 'payment_collected', '$50 deposit collected', 'Erica Patel''s HVAC appointment is confirmed and marked prepaid.', 'normal', '/jobs', 'opened')
on conflict (id) do nothing;

insert into notifications (id, business_id, type, title, body, priority, destination, status)
values ('notif-photo-upload', 'business-bayview', 'customer_photo', 'Photos received', 'Two under-sink photos were attached to Angela Brooks'' emergency call.', 'important', '/customers', 'sent')
on conflict (id) do nothing;

insert into notifications (id, business_id, type, title, body, priority, destination, status)
values ('notif-after-hours', 'business-bayview', 'after_hours_lead', 'After-hours lead booked', 'Garage door spring call was handled by Trowel and booked for tomorrow morning.', 'normal', '/calls', 'opened')
on conflict (id) do nothing;

insert into notifications (id, business_id, type, title, body, priority, destination, status)
values ('notif-sms-review', 'business-bayview', 'calendar_sync_failure', 'Calendar sync needs attention', 'One external calendar update needs review before Trowel can trust that slot.', 'important', '/settings', 'queued')
on conflict (id) do nothing;

insert into notification_delivery_events (id, business_id, notification_id, channel, status, detail)
values ('delivery-angela-push', 'business-bayview', 'notif-angela-emergency', 'push', 'sent', '4 min ago - Push delivered to owner and dispatcher.')
on conflict (id) do nothing;

insert into notification_delivery_events (id, business_id, notification_id, channel, status, detail)
values ('delivery-angela-sms', 'business-bayview', 'notif-angela-emergency', 'sms', 'sent', '4 min ago - SMS fallback delivered to owner.')
on conflict (id) do nothing;

insert into notification_delivery_events (id, business_id, notification_id, channel, status, detail)
values ('delivery-lily-push', 'business-bayview', 'notif-lily-payment', 'push', 'sent', '8 min ago - Push delivered to dispatcher.')
on conflict (id) do nothing;

insert into notification_delivery_events (id, business_id, notification_id, channel, status, detail)
values ('delivery-sync-queued', 'business-bayview', 'notif-sms-review', 'push', 'queued', '2 hr ago - Waiting on notification worker.')
on conflict (id) do nothing;

insert into onboarding_confirmations (id, business_id, card_id, status, fields)
values ('business-profile', 'business-bayview', 'business-profile', 'confirmed', '[{"id":"business-name","label":"Business name","value":"Bayview HVAC & Plumbing","confidence":96,"sourceUrl":"https://bayviewhvacplumbing.example/","editable":true,"requiresConfirmation":false,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"public-phone","label":"Public phone","value":"(510) 555-0142","confidence":92,"sourceUrl":"https://bayviewhvacplumbing.example/contact","editable":true,"requiresConfirmation":false,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"address","label":"Primary address","value":"Hayward, CA","confidence":89,"sourceUrl":"https://bayviewhvacplumbing.example/contact","editable":true,"requiresConfirmation":true,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"trade-category","label":"Trade category","value":"HVAC and plumbing","confidence":91,"sourceUrl":"https://bayviewhvacplumbing.example/services","editable":true,"requiresConfirmation":false,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"}]'::jsonb)
on conflict (id) do nothing;

insert into onboarding_confirmations (id, business_id, card_id, status, fields)
values ('services', 'business-bayview', 'services', 'review', '[{"id":"hvac-services","label":"HVAC services","value":"No cooling, tune-ups, thermostat issues, emergency heat","confidence":88,"sourceUrl":"https://bayviewhvacplumbing.example/services/hvac","editable":true,"requiresConfirmation":true,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"plumbing-services","label":"Plumbing services","value":"Burst pipe, clogged drain, sewer backup, leak repair","confidence":90,"sourceUrl":"https://bayviewhvacplumbing.example/services/plumbing","editable":true,"requiresConfirmation":false,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"excluded-services","label":"Excluded services","value":"Major remodels and warranty pricing not confirmed","confidence":58,"sourceUrl":"https://bayviewhvacplumbing.example/faq","editable":true,"requiresConfirmation":true,"confirmed":false,"timestamp":"2026-05-14T21:58:00-07:00"}]'::jsonb)
on conflict (id) do nothing;

insert into onboarding_confirmations (id, business_id, card_id, status, fields)
values ('hours', 'business-bayview', 'hours', 'review', '[{"id":"business-hours","label":"Business hours","value":"Mon-Sat, 7:00 AM - 7:00 PM","confidence":86,"sourceUrl":"https://bayviewhvacplumbing.example/contact","editable":true,"requiresConfirmation":true,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"after-hours","label":"After-hours handling","value":"Answer every call, qualify, hold emergency slots, escalate urgent work","confidence":81,"sourceUrl":"https://bayviewhvacplumbing.example/emergency","editable":true,"requiresConfirmation":true,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"emergency-availability","label":"Emergency availability","value":"Plumbing emergencies available with owner approval","confidence":72,"sourceUrl":"https://bayviewhvacplumbing.example/emergency","editable":true,"requiresConfirmation":true,"confirmed":false,"timestamp":"2026-05-14T21:58:00-07:00"}]'::jsonb)
on conflict (id) do nothing;

insert into onboarding_confirmations (id, business_id, card_id, status, fields)
values ('service-area', 'business-bayview', 'service-area', 'confirmed', '[{"id":"cities","label":"Cities served","value":"Hayward, Oakland, Fremont, San Leandro, Union City","confidence":93,"sourceUrl":"https://bayviewhvacplumbing.example/service-area","editable":true,"requiresConfirmation":false,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"zip-codes","label":"ZIP coverage","value":"12 ZIP codes detected","confidence":84,"sourceUrl":"https://bayviewhvacplumbing.example/sitemap.xml","editable":true,"requiresConfirmation":true,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"travel-buffer","label":"Travel buffer","value":"20-45 minutes by zone","confidence":76,"sourceUrl":"internal://routing","editable":true,"requiresConfirmation":true,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"}]'::jsonb)
on conflict (id) do nothing;

insert into onboarding_confirmations (id, business_id, card_id, status, fields)
values ('calendar-rules', 'business-bayview', 'calendar-rules', 'review', '[{"id":"source-of-truth","label":"Source of truth","value":"Connected calendar, internal fallback, manual approval for uncertainty","confidence":90,"sourceUrl":"internal://scheduling","editable":true,"requiresConfirmation":false,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"technician-count","label":"Team size","value":"3 technicians","confidence":100,"sourceUrl":"internal://team","editable":true,"requiresConfirmation":false,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"emergency-holds","label":"Emergency holds","value":"Protected slots can be held, not confirmed, until dispatcher approval","confidence":95,"sourceUrl":"internal://dispatch","editable":true,"requiresConfirmation":false,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"}]'::jsonb)
on conflict (id) do nothing;

insert into onboarding_confirmations (id, business_id, card_id, status, fields)
values ('communications', 'business-bayview', 'communications', 'review', '[{"id":"existing-number","label":"Public business number","value":"(510) 555-0142 stays public","confidence":100,"sourceUrl":"internal://communications","editable":true,"requiresConfirmation":false,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"ai-voice-number","label":"AI voice number","value":"(510) 555-0440 receives forwarded calls","confidence":100,"sourceUrl":"internal://communications","editable":true,"requiresConfirmation":false,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"ai-texting-number","label":"AI texting number","value":"(510) 555-0441 sends confirmations, photos, payments, and updates","confidence":100,"sourceUrl":"internal://communications","editable":true,"requiresConfirmation":false,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"sms-compliance","label":"SMS verification","value":"A2P registration runs in the background and does not block voice activation","confidence":100,"sourceUrl":"internal://communications","editable":true,"requiresConfirmation":false,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"porting","label":"Future porting","value":"Optional later upgrade. Not required for MVP activation.","confidence":100,"sourceUrl":"internal://communications","editable":true,"requiresConfirmation":false,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"}]'::jsonb)
on conflict (id) do nothing;

insert into onboarding_confirmations (id, business_id, card_id, status, fields)
values ('payments', 'business-bayview', 'payments', 'blocked', '[{"id":"policy-standard-diagnostic","label":"Standard diagnostic fee","value":"$89 - Use for standard non-emergency diagnostic visits when no membership waiver applies.","confidence":100,"sourceUrl":"internal://payments","editable":true,"requiresConfirmation":false,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"policy-emergency-plumbing","label":"Plumbing emergency deposit","value":"$150 - Suggested emergency deposit. Owner confirmation required before AI can request this amount.","confidence":64,"sourceUrl":"internal://payments","editable":true,"requiresConfirmation":true,"confirmed":false,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"policy-membership-waiver","label":"Membership booking waiver","value":"Do not require payment before booking for active members.","confidence":100,"sourceUrl":"internal://payments","editable":true,"requiresConfirmation":false,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"},{"id":"policy-owner-quote","label":"Owner must quote","value":"Used when service price or deposit rule is unclear. AI escalates instead of inventing a price.","confidence":100,"sourceUrl":"internal://payments","editable":true,"requiresConfirmation":false,"confirmed":true,"timestamp":"2026-05-14T21:58:00-07:00"}]'::jsonb)
on conflict (id) do nothing;

commit;
