/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as DownloadAppRouteImport } from './routes/download-app'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as ApiTeamRouteImport } from './routes/api.team'
import { Route as ApiOnboardingRouteImport } from './routes/api.onboarding'
import { Route as ApiNotificationsRouteImport } from './routes/api.notifications'
import { Route as ApiMeRouteImport } from './routes/api.me'
import { Route as ApiJobsRouteImport } from './routes/api.jobs'
import { Route as ApiInboxRouteImport } from './routes/api.inbox'
import { Route as ApiDispatchRouteImport } from './routes/api.dispatch'
import { Route as ApiCustomersRouteImport } from './routes/api.customers'
import { Route as ApiCallsRouteImport } from './routes/api.calls'
import { Route as ApiCalendarRouteImport } from './routes/api.calendar'
import { Route as ApiAuditLogRouteImport } from './routes/api.audit-log'
import { Route as ApiWebhooksStripePlatformRouteImport } from './routes/api.webhooks.stripe-platform'
import { Route as ApiWebhooksStripeConnectRouteImport } from './routes/api.webhooks.stripe-connect'
import { Route as ApiSignupStartRouteImport } from './routes/api.signup.start'
import { Route as ApiSettingsReadinessRouteImport } from './routes/api.settings.readiness'
import { Route as ApiPaymentsRequestsRouteImport } from './routes/api.payments.requests'
import { Route as ApiMobileSnapshotRouteImport } from './routes/api.mobile.snapshot'
import { Route as ApiMeEntitlementsRouteImport } from './routes/api.me.entitlements'
import { Route as ApiConnectStatusRouteImport } from './routes/api.connect.status'
import { Route as ApiConnectOnboardingLinkRouteImport } from './routes/api.connect.onboarding-link'
import { Route as ApiBillingSubscriptionRouteImport } from './routes/api.billing.subscription'
import { Route as ApiBillingCustomerPortalRouteImport } from './routes/api.billing.customer-portal'
import { Route as ApiBillingCheckoutSessionRouteImport } from './routes/api.billing.checkout-session'
import { Route as ApiWebhooksTwilioVoiceRouteImport } from './routes/api.webhooks.twilio.voice'
import { Route as ApiWebhooksTwilioSmsRouteImport } from './routes/api.webhooks.twilio.sms'
import { Route as ApiJobsJobIdStatusRouteImport } from './routes/api.jobs.$jobId.status'
import { Route as ApiJobsJobIdPaymentsRouteImport } from './routes/api.jobs.$jobId.payments'
import { Route as ApiJobsJobIdPaymentLinkRouteImport } from './routes/api.jobs.$jobId.payment-link'
import { Route as ApiJobsJobIdInvoicesRouteImport } from './routes/api.jobs.$jobId.invoices'
import { Route as ApiDispatchDispatchIdAssignRouteImport } from './routes/api.dispatch.$dispatchId.assign'
import { Route as ApiDispatchDispatchIdApproveRouteImport } from './routes/api.dispatch.$dispatchId.approve'
import { Route as ApiChannelsTwilioStatusRouteImport } from './routes/api.channels.twilio.status'
import { Route as ApiChannelsTwilioProvisionNumberRouteImport } from './routes/api.channels.twilio.provision-number'
import { Route as ApiBusinessesBusinessIdStatusRouteImport } from './routes/api.businesses.$businessId.status'
import { Route as ApiChannelsTwilioA2pSubmitRouteImport } from './routes/api.channels.twilio.a2p.submit'

const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadAppRoute = DownloadAppRouteImport.update({
  id: '/download-app',
  path: '/download-app',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)
const ApiTeamRoute = ApiTeamRouteImport.update({
  id: '/api/team',
  path: '/api/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingRoute = ApiOnboardingRouteImport.update({
  id: '/api/onboarding',
  path: '/api/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxRoute = ApiInboxRouteImport.update({
  id: '/api/inbox',
  path: '/api/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDispatchRoute = ApiDispatchRouteImport.update({
  id: '/api/dispatch',
  path: '/api/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomersRoute = ApiCustomersRouteImport.update({
  id: '/api/customers',
  path: '/api/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsRoute = ApiCallsRouteImport.update({
  id: '/api/calls',
  path: '/api/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarRoute = ApiCalendarRouteImport.update({
  id: '/api/calendar',
  path: '/api/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditLogRoute = ApiAuditLogRouteImport.update({
  id: '/api/audit-log',
  path: '/api/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripePlatformRoute =
  ApiWebhooksStripePlatformRouteImport.update({
    id: '/api/webhooks/stripe-platform',
    path: '/api/webhooks/stripe-platform',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksStripeConnectRoute =
  ApiWebhooksStripeConnectRouteImport.update({
    id: '/api/webhooks/stripe-connect',
    path: '/api/webhooks/stripe-connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSignupStartRoute = ApiSignupStartRouteImport.update({
  id: '/api/signup/start',
  path: '/api/signup/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsReadinessRoute = ApiSettingsReadinessRouteImport.update({
  id: '/api/settings/readiness',
  path: '/api/settings/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsRequestsRoute = ApiPaymentsRequestsRouteImport.update({
  id: '/api/payments/requests',
  path: '/api/payments/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileSnapshotRoute = ApiMobileSnapshotRouteImport.update({
  id: '/api/mobile/snapshot',
  path: '/api/mobile/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeEntitlementsRoute = ApiMeEntitlementsRouteImport.update({
  id: '/entitlements',
  path: '/entitlements',
  getParentRoute: () => ApiMeRoute,
} as any)
const ApiConnectStatusRoute = ApiConnectStatusRouteImport.update({
  id: '/api/connect/status',
  path: '/api/connect/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectOnboardingLinkRoute =
  ApiConnectOnboardingLinkRouteImport.update({
    id: '/api/connect/onboarding-link',
    path: '/api/connect/onboarding-link',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingSubscriptionRoute = ApiBillingSubscriptionRouteImport.update({
  id: '/api/billing/subscription',
  path: '/api/billing/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCustomerPortalRoute =
  ApiBillingCustomerPortalRouteImport.update({
    id: '/api/billing/customer-portal',
    path: '/api/billing/customer-portal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBillingCheckoutSessionRoute =
  ApiBillingCheckoutSessionRouteImport.update({
    id: '/api/billing/checkout-session',
    path: '/api/billing/checkout-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksTwilioVoiceRoute = ApiWebhooksTwilioVoiceRouteImport.update({
  id: '/api/webhooks/twilio/voice',
  path: '/api/webhooks/twilio/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksTwilioSmsRoute = ApiWebhooksTwilioSmsRouteImport.update({
  id: '/api/webhooks/twilio/sms',
  path: '/api/webhooks/twilio/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsJobIdStatusRoute = ApiJobsJobIdStatusRouteImport.update({
  id: '/$jobId/status',
  path: '/$jobId/status',
  getParentRoute: () => ApiJobsRoute,
} as any)
const ApiJobsJobIdPaymentsRoute = ApiJobsJobIdPaymentsRouteImport.update({
  id: '/$jobId/payments',
  path: '/$jobId/payments',
  getParentRoute: () => ApiJobsRoute,
} as any)
const ApiJobsJobIdPaymentLinkRoute = ApiJobsJobIdPaymentLinkRouteImport.update({
  id: '/$jobId/payment-link',
  path: '/$jobId/payment-link',
  getParentRoute: () => ApiJobsRoute,
} as any)
const ApiJobsJobIdInvoicesRoute = ApiJobsJobIdInvoicesRouteImport.update({
  id: '/$jobId/invoices',
  path: '/$jobId/invoices',
  getParentRoute: () => ApiJobsRoute,
} as any)
const ApiDispatchDispatchIdAssignRoute =
  ApiDispatchDispatchIdAssignRouteImport.update({
    id: '/$dispatchId/assign',
    path: '/$dispatchId/assign',
    getParentRoute: () => ApiDispatchRoute,
  } as any)
const ApiDispatchDispatchIdApproveRoute =
  ApiDispatchDispatchIdApproveRouteImport.update({
    id: '/$dispatchId/approve',
    path: '/$dispatchId/approve',
    getParentRoute: () => ApiDispatchRoute,
  } as any)
const ApiChannelsTwilioStatusRoute = ApiChannelsTwilioStatusRouteImport.update({
  id: '/api/channels/twilio/status',
  path: '/api/channels/twilio/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelsTwilioProvisionNumberRoute =
  ApiChannelsTwilioProvisionNumberRouteImport.update({
    id: '/api/channels/twilio/provision-number',
    path: '/api/channels/twilio/provision-number',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBusinessesBusinessIdStatusRoute =
  ApiBusinessesBusinessIdStatusRouteImport.update({
    id: '/api/businesses/$businessId/status',
    path: '/api/businesses/$businessId/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChannelsTwilioA2pSubmitRoute =
  ApiChannelsTwilioA2pSubmitRouteImport.update({
    id: '/api/channels/twilio/a2p/submit',
    path: '/api/channels/twilio/a2p/submit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dispatch': typeof DispatchRoute
  '/download-app': typeof DownloadAppRoute
  '/invoices': typeof InvoicesRoute
  '/jobs': typeof JobsRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/website': typeof WebsiteRoute
  '/api/audit-log': typeof ApiAuditLogRoute
  '/api/calendar': typeof ApiCalendarRoute
  '/api/calls': typeof ApiCallsRoute
  '/api/customers': typeof ApiCustomersRoute
  '/api/dispatch': typeof ApiDispatchRouteWithChildren
  '/api/inbox': typeof ApiInboxRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/me': typeof ApiMeRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/api/team': typeof ApiTeamRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/api/billing/checkout-session': typeof ApiBillingCheckoutSessionRoute
  '/api/billing/customer-portal': typeof ApiBillingCustomerPortalRoute
  '/api/billing/subscription': typeof ApiBillingSubscriptionRoute
  '/api/connect/onboarding-link': typeof ApiConnectOnboardingLinkRoute
  '/api/connect/status': typeof ApiConnectStatusRoute
  '/api/me/entitlements': typeof ApiMeEntitlementsRoute
  '/api/mobile/snapshot': typeof ApiMobileSnapshotRoute
  '/api/payments/requests': typeof ApiPaymentsRequestsRoute
  '/api/settings/readiness': typeof ApiSettingsReadinessRoute
  '/api/signup/start': typeof ApiSignupStartRoute
  '/api/webhooks/stripe-connect': typeof ApiWebhooksStripeConnectRoute
  '/api/webhooks/stripe-platform': typeof ApiWebhooksStripePlatformRoute
  '/api/businesses/$businessId/status': typeof ApiBusinessesBusinessIdStatusRoute
  '/api/channels/twilio/provision-number': typeof ApiChannelsTwilioProvisionNumberRoute
  '/api/channels/twilio/status': typeof ApiChannelsTwilioStatusRoute
  '/api/dispatch/$dispatchId/approve': typeof ApiDispatchDispatchIdApproveRoute
  '/api/dispatch/$dispatchId/assign': typeof ApiDispatchDispatchIdAssignRoute
  '/api/jobs/$jobId/invoices': typeof ApiJobsJobIdInvoicesRoute
  '/api/jobs/$jobId/payment-link': typeof ApiJobsJobIdPaymentLinkRoute
  '/api/jobs/$jobId/payments': typeof ApiJobsJobIdPaymentsRoute
  '/api/jobs/$jobId/status': typeof ApiJobsJobIdStatusRoute
  '/api/webhooks/twilio/sms': typeof ApiWebhooksTwilioSmsRoute
  '/api/webhooks/twilio/voice': typeof ApiWebhooksTwilioVoiceRoute
  '/api/channels/twilio/a2p/submit': typeof ApiChannelsTwilioA2pSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dispatch': typeof DispatchRoute
  '/download-app': typeof DownloadAppRoute
  '/invoices': typeof InvoicesRoute
  '/jobs': typeof JobsRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/website': typeof WebsiteRoute
  '/api/audit-log': typeof ApiAuditLogRoute
  '/api/calendar': typeof ApiCalendarRoute
  '/api/calls': typeof ApiCallsRoute
  '/api/customers': typeof ApiCustomersRoute
  '/api/dispatch': typeof ApiDispatchRouteWithChildren
  '/api/inbox': typeof ApiInboxRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/me': typeof ApiMeRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/api/team': typeof ApiTeamRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/api/billing/checkout-session': typeof ApiBillingCheckoutSessionRoute
  '/api/billing/customer-portal': typeof ApiBillingCustomerPortalRoute
  '/api/billing/subscription': typeof ApiBillingSubscriptionRoute
  '/api/connect/onboarding-link': typeof ApiConnectOnboardingLinkRoute
  '/api/connect/status': typeof ApiConnectStatusRoute
  '/api/me/entitlements': typeof ApiMeEntitlementsRoute
  '/api/mobile/snapshot': typeof ApiMobileSnapshotRoute
  '/api/payments/requests': typeof ApiPaymentsRequestsRoute
  '/api/settings/readiness': typeof ApiSettingsReadinessRoute
  '/api/signup/start': typeof ApiSignupStartRoute
  '/api/webhooks/stripe-connect': typeof ApiWebhooksStripeConnectRoute
  '/api/webhooks/stripe-platform': typeof ApiWebhooksStripePlatformRoute
  '/api/businesses/$businessId/status': typeof ApiBusinessesBusinessIdStatusRoute
  '/api/channels/twilio/provision-number': typeof ApiChannelsTwilioProvisionNumberRoute
  '/api/channels/twilio/status': typeof ApiChannelsTwilioStatusRoute
  '/api/dispatch/$dispatchId/approve': typeof ApiDispatchDispatchIdApproveRoute
  '/api/dispatch/$dispatchId/assign': typeof ApiDispatchDispatchIdAssignRoute
  '/api/jobs/$jobId/invoices': typeof ApiJobsJobIdInvoicesRoute
  '/api/jobs/$jobId/payment-link': typeof ApiJobsJobIdPaymentLinkRoute
  '/api/jobs/$jobId/payments': typeof ApiJobsJobIdPaymentsRoute
  '/api/jobs/$jobId/status': typeof ApiJobsJobIdStatusRoute
  '/api/webhooks/twilio/sms': typeof ApiWebhooksTwilioSmsRoute
  '/api/webhooks/twilio/voice': typeof ApiWebhooksTwilioVoiceRoute
  '/api/channels/twilio/a2p/submit': typeof ApiChannelsTwilioA2pSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dispatch': typeof DispatchRoute
  '/download-app': typeof DownloadAppRoute
  '/invoices': typeof InvoicesRoute
  '/jobs': typeof JobsRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/website': typeof WebsiteRoute
  '/api/audit-log': typeof ApiAuditLogRoute
  '/api/calendar': typeof ApiCalendarRoute
  '/api/calls': typeof ApiCallsRoute
  '/api/customers': typeof ApiCustomersRoute
  '/api/dispatch': typeof ApiDispatchRouteWithChildren
  '/api/inbox': typeof ApiInboxRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/me': typeof ApiMeRouteWithChildren
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/api/team': typeof ApiTeamRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/api/billing/checkout-session': typeof ApiBillingCheckoutSessionRoute
  '/api/billing/customer-portal': typeof ApiBillingCustomerPortalRoute
  '/api/billing/subscription': typeof ApiBillingSubscriptionRoute
  '/api/connect/onboarding-link': typeof ApiConnectOnboardingLinkRoute
  '/api/connect/status': typeof ApiConnectStatusRoute
  '/api/me/entitlements': typeof ApiMeEntitlementsRoute
  '/api/mobile/snapshot': typeof ApiMobileSnapshotRoute
  '/api/payments/requests': typeof ApiPaymentsRequestsRoute
  '/api/settings/readiness': typeof ApiSettingsReadinessRoute
  '/api/signup/start': typeof ApiSignupStartRoute
  '/api/webhooks/stripe-connect': typeof ApiWebhooksStripeConnectRoute
  '/api/webhooks/stripe-platform': typeof ApiWebhooksStripePlatformRoute
  '/api/businesses/$businessId/status': typeof ApiBusinessesBusinessIdStatusRoute
  '/api/channels/twilio/provision-number': typeof ApiChannelsTwilioProvisionNumberRoute
  '/api/channels/twilio/status': typeof ApiChannelsTwilioStatusRoute
  '/api/dispatch/$dispatchId/approve': typeof ApiDispatchDispatchIdApproveRoute
  '/api/dispatch/$dispatchId/assign': typeof ApiDispatchDispatchIdAssignRoute
  '/api/jobs/$jobId/invoices': typeof ApiJobsJobIdInvoicesRoute
  '/api/jobs/$jobId/payment-link': typeof ApiJobsJobIdPaymentLinkRoute
  '/api/jobs/$jobId/payments': typeof ApiJobsJobIdPaymentsRoute
  '/api/jobs/$jobId/status': typeof ApiJobsJobIdStatusRoute
  '/api/webhooks/twilio/sms': typeof ApiWebhooksTwilioSmsRoute
  '/api/webhooks/twilio/voice': typeof ApiWebhooksTwilioVoiceRoute
  '/api/channels/twilio/a2p/submit': typeof ApiChannelsTwilioA2pSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calls'
    | '/customers'
    | '/dispatch'
    | '/download-app'
    | '/invoices'
    | '/jobs'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/portal'
    | '/pricing'
    | '/settings'
    | '/signup'
    | '/team'
    | '/website'
    | '/api/audit-log'
    | '/api/calendar'
    | '/api/calls'
    | '/api/customers'
    | '/api/dispatch'
    | '/api/inbox'
    | '/api/jobs'
    | '/api/me'
    | '/api/notifications'
    | '/api/onboarding'
    | '/api/team'
    | '/customers/$customerId'
    | '/api/billing/checkout-session'
    | '/api/billing/customer-portal'
    | '/api/billing/subscription'
    | '/api/connect/onboarding-link'
    | '/api/connect/status'
    | '/api/me/entitlements'
    | '/api/mobile/snapshot'
    | '/api/payments/requests'
    | '/api/settings/readiness'
    | '/api/signup/start'
    | '/api/webhooks/stripe-connect'
    | '/api/webhooks/stripe-platform'
    | '/api/businesses/$businessId/status'
    | '/api/channels/twilio/provision-number'
    | '/api/channels/twilio/status'
    | '/api/dispatch/$dispatchId/approve'
    | '/api/dispatch/$dispatchId/assign'
    | '/api/jobs/$jobId/invoices'
    | '/api/jobs/$jobId/payment-link'
    | '/api/jobs/$jobId/payments'
    | '/api/jobs/$jobId/status'
    | '/api/webhooks/twilio/sms'
    | '/api/webhooks/twilio/voice'
    | '/api/channels/twilio/a2p/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calls'
    | '/customers'
    | '/dispatch'
    | '/download-app'
    | '/invoices'
    | '/jobs'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/portal'
    | '/pricing'
    | '/settings'
    | '/signup'
    | '/team'
    | '/website'
    | '/api/audit-log'
    | '/api/calendar'
    | '/api/calls'
    | '/api/customers'
    | '/api/dispatch'
    | '/api/inbox'
    | '/api/jobs'
    | '/api/me'
    | '/api/notifications'
    | '/api/onboarding'
    | '/api/team'
    | '/customers/$customerId'
    | '/api/billing/checkout-session'
    | '/api/billing/customer-portal'
    | '/api/billing/subscription'
    | '/api/connect/onboarding-link'
    | '/api/connect/status'
    | '/api/me/entitlements'
    | '/api/mobile/snapshot'
    | '/api/payments/requests'
    | '/api/settings/readiness'
    | '/api/signup/start'
    | '/api/webhooks/stripe-connect'
    | '/api/webhooks/stripe-platform'
    | '/api/businesses/$businessId/status'
    | '/api/channels/twilio/provision-number'
    | '/api/channels/twilio/status'
    | '/api/dispatch/$dispatchId/approve'
    | '/api/dispatch/$dispatchId/assign'
    | '/api/jobs/$jobId/invoices'
    | '/api/jobs/$jobId/payment-link'
    | '/api/jobs/$jobId/payments'
    | '/api/jobs/$jobId/status'
    | '/api/webhooks/twilio/sms'
    | '/api/webhooks/twilio/voice'
    | '/api/channels/twilio/a2p/submit'
  id:
    | '__root__'
    | '/'
    | '/calls'
    | '/customers'
    | '/dispatch'
    | '/download-app'
    | '/invoices'
    | '/jobs'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/portal'
    | '/pricing'
    | '/settings'
    | '/signup'
    | '/team'
    | '/website'
    | '/api/audit-log'
    | '/api/calendar'
    | '/api/calls'
    | '/api/customers'
    | '/api/dispatch'
    | '/api/inbox'
    | '/api/jobs'
    | '/api/me'
    | '/api/notifications'
    | '/api/onboarding'
    | '/api/team'
    | '/customers/$customerId'
    | '/api/billing/checkout-session'
    | '/api/billing/customer-portal'
    | '/api/billing/subscription'
    | '/api/connect/onboarding-link'
    | '/api/connect/status'
    | '/api/me/entitlements'
    | '/api/mobile/snapshot'
    | '/api/payments/requests'
    | '/api/settings/readiness'
    | '/api/signup/start'
    | '/api/webhooks/stripe-connect'
    | '/api/webhooks/stripe-platform'
    | '/api/businesses/$businessId/status'
    | '/api/channels/twilio/provision-number'
    | '/api/channels/twilio/status'
    | '/api/dispatch/$dispatchId/approve'
    | '/api/dispatch/$dispatchId/assign'
    | '/api/jobs/$jobId/invoices'
    | '/api/jobs/$jobId/payment-link'
    | '/api/jobs/$jobId/payments'
    | '/api/jobs/$jobId/status'
    | '/api/webhooks/twilio/sms'
    | '/api/webhooks/twilio/voice'
    | '/api/channels/twilio/a2p/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallsRoute: typeof CallsRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DispatchRoute: typeof DispatchRoute
  DownloadAppRoute: typeof DownloadAppRoute
  InvoicesRoute: typeof InvoicesRoute
  JobsRoute: typeof JobsRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PortalRoute: typeof PortalRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TeamRoute: typeof TeamRoute
  WebsiteRoute: typeof WebsiteRoute
  ApiAuditLogRoute: typeof ApiAuditLogRoute
  ApiCalendarRoute: typeof ApiCalendarRoute
  ApiCallsRoute: typeof ApiCallsRoute
  ApiCustomersRoute: typeof ApiCustomersRoute
  ApiDispatchRoute: typeof ApiDispatchRouteWithChildren
  ApiInboxRoute: typeof ApiInboxRoute
  ApiJobsRoute: typeof ApiJobsRouteWithChildren
  ApiMeRoute: typeof ApiMeRouteWithChildren
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiOnboardingRoute: typeof ApiOnboardingRoute
  ApiTeamRoute: typeof ApiTeamRoute
  ApiBillingCheckoutSessionRoute: typeof ApiBillingCheckoutSessionRoute
  ApiBillingCustomerPortalRoute: typeof ApiBillingCustomerPortalRoute
  ApiBillingSubscriptionRoute: typeof ApiBillingSubscriptionRoute
  ApiConnectOnboardingLinkRoute: typeof ApiConnectOnboardingLinkRoute
  ApiConnectStatusRoute: typeof ApiConnectStatusRoute
  ApiMobileSnapshotRoute: typeof ApiMobileSnapshotRoute
  ApiPaymentsRequestsRoute: typeof ApiPaymentsRequestsRoute
  ApiSettingsReadinessRoute: typeof ApiSettingsReadinessRoute
  ApiSignupStartRoute: typeof ApiSignupStartRoute
  ApiWebhooksStripeConnectRoute: typeof ApiWebhooksStripeConnectRoute
  ApiWebhooksStripePlatformRoute: typeof ApiWebhooksStripePlatformRoute
  ApiBusinessesBusinessIdStatusRoute: typeof ApiBusinessesBusinessIdStatusRoute
  ApiChannelsTwilioProvisionNumberRoute: typeof ApiChannelsTwilioProvisionNumberRoute
  ApiChannelsTwilioStatusRoute: typeof ApiChannelsTwilioStatusRoute
  ApiWebhooksTwilioSmsRoute: typeof ApiWebhooksTwilioSmsRoute
  ApiWebhooksTwilioVoiceRoute: typeof ApiWebhooksTwilioVoiceRoute
  ApiChannelsTwilioA2pSubmitRoute: typeof ApiChannelsTwilioA2pSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download-app': {
      id: '/download-app'
      path: '/download-app'
      fullPath: '/download-app'
      preLoaderRoute: typeof DownloadAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/api/team': {
      id: '/api/team'
      path: '/api/team'
      fullPath: '/api/team'
      preLoaderRoute: typeof ApiTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding': {
      id: '/api/onboarding'
      path: '/api/onboarding'
      fullPath: '/api/onboarding'
      preLoaderRoute: typeof ApiOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox': {
      id: '/api/inbox'
      path: '/api/inbox'
      fullPath: '/api/inbox'
      preLoaderRoute: typeof ApiInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dispatch': {
      id: '/api/dispatch'
      path: '/api/dispatch'
      fullPath: '/api/dispatch'
      preLoaderRoute: typeof ApiDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customers': {
      id: '/api/customers'
      path: '/api/customers'
      fullPath: '/api/customers'
      preLoaderRoute: typeof ApiCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls': {
      id: '/api/calls'
      path: '/api/calls'
      fullPath: '/api/calls'
      preLoaderRoute: typeof ApiCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar': {
      id: '/api/calendar'
      path: '/api/calendar'
      fullPath: '/api/calendar'
      preLoaderRoute: typeof ApiCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit-log': {
      id: '/api/audit-log'
      path: '/api/audit-log'
      fullPath: '/api/audit-log'
      preLoaderRoute: typeof ApiAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe-platform': {
      id: '/api/webhooks/stripe-platform'
      path: '/api/webhooks/stripe-platform'
      fullPath: '/api/webhooks/stripe-platform'
      preLoaderRoute: typeof ApiWebhooksStripePlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe-connect': {
      id: '/api/webhooks/stripe-connect'
      path: '/api/webhooks/stripe-connect'
      fullPath: '/api/webhooks/stripe-connect'
      preLoaderRoute: typeof ApiWebhooksStripeConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signup/start': {
      id: '/api/signup/start'
      path: '/api/signup/start'
      fullPath: '/api/signup/start'
      preLoaderRoute: typeof ApiSignupStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/readiness': {
      id: '/api/settings/readiness'
      path: '/api/settings/readiness'
      fullPath: '/api/settings/readiness'
      preLoaderRoute: typeof ApiSettingsReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/requests': {
      id: '/api/payments/requests'
      path: '/api/payments/requests'
      fullPath: '/api/payments/requests'
      preLoaderRoute: typeof ApiPaymentsRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/snapshot': {
      id: '/api/mobile/snapshot'
      path: '/api/mobile/snapshot'
      fullPath: '/api/mobile/snapshot'
      preLoaderRoute: typeof ApiMobileSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/entitlements': {
      id: '/api/me/entitlements'
      path: '/entitlements'
      fullPath: '/api/me/entitlements'
      preLoaderRoute: typeof ApiMeEntitlementsRouteImport
      parentRoute: typeof ApiMeRoute
    }
    '/api/connect/status': {
      id: '/api/connect/status'
      path: '/api/connect/status'
      fullPath: '/api/connect/status'
      preLoaderRoute: typeof ApiConnectStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connect/onboarding-link': {
      id: '/api/connect/onboarding-link'
      path: '/api/connect/onboarding-link'
      fullPath: '/api/connect/onboarding-link'
      preLoaderRoute: typeof ApiConnectOnboardingLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/subscription': {
      id: '/api/billing/subscription'
      path: '/api/billing/subscription'
      fullPath: '/api/billing/subscription'
      preLoaderRoute: typeof ApiBillingSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/customer-portal': {
      id: '/api/billing/customer-portal'
      path: '/api/billing/customer-portal'
      fullPath: '/api/billing/customer-portal'
      preLoaderRoute: typeof ApiBillingCustomerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout-session': {
      id: '/api/billing/checkout-session'
      path: '/api/billing/checkout-session'
      fullPath: '/api/billing/checkout-session'
      preLoaderRoute: typeof ApiBillingCheckoutSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/twilio/voice': {
      id: '/api/webhooks/twilio/voice'
      path: '/api/webhooks/twilio/voice'
      fullPath: '/api/webhooks/twilio/voice'
      preLoaderRoute: typeof ApiWebhooksTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/twilio/sms': {
      id: '/api/webhooks/twilio/sms'
      path: '/api/webhooks/twilio/sms'
      fullPath: '/api/webhooks/twilio/sms'
      preLoaderRoute: typeof ApiWebhooksTwilioSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$jobId/status': {
      id: '/api/jobs/$jobId/status'
      path: '/$jobId/status'
      fullPath: '/api/jobs/$jobId/status'
      preLoaderRoute: typeof ApiJobsJobIdStatusRouteImport
      parentRoute: typeof ApiJobsRoute
    }
    '/api/jobs/$jobId/payments': {
      id: '/api/jobs/$jobId/payments'
      path: '/$jobId/payments'
      fullPath: '/api/jobs/$jobId/payments'
      preLoaderRoute: typeof ApiJobsJobIdPaymentsRouteImport
      parentRoute: typeof ApiJobsRoute
    }
    '/api/jobs/$jobId/payment-link': {
      id: '/api/jobs/$jobId/payment-link'
      path: '/$jobId/payment-link'
      fullPath: '/api/jobs/$jobId/payment-link'
      preLoaderRoute: typeof ApiJobsJobIdPaymentLinkRouteImport
      parentRoute: typeof ApiJobsRoute
    }
    '/api/jobs/$jobId/invoices': {
      id: '/api/jobs/$jobId/invoices'
      path: '/$jobId/invoices'
      fullPath: '/api/jobs/$jobId/invoices'
      preLoaderRoute: typeof ApiJobsJobIdInvoicesRouteImport
      parentRoute: typeof ApiJobsRoute
    }
    '/api/dispatch/$dispatchId/assign': {
      id: '/api/dispatch/$dispatchId/assign'
      path: '/$dispatchId/assign'
      fullPath: '/api/dispatch/$dispatchId/assign'
      preLoaderRoute: typeof ApiDispatchDispatchIdAssignRouteImport
      parentRoute: typeof ApiDispatchRoute
    }
    '/api/dispatch/$dispatchId/approve': {
      id: '/api/dispatch/$dispatchId/approve'
      path: '/$dispatchId/approve'
      fullPath: '/api/dispatch/$dispatchId/approve'
      preLoaderRoute: typeof ApiDispatchDispatchIdApproveRouteImport
      parentRoute: typeof ApiDispatchRoute
    }
    '/api/channels/twilio/status': {
      id: '/api/channels/twilio/status'
      path: '/api/channels/twilio/status'
      fullPath: '/api/channels/twilio/status'
      preLoaderRoute: typeof ApiChannelsTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels/twilio/provision-number': {
      id: '/api/channels/twilio/provision-number'
      path: '/api/channels/twilio/provision-number'
      fullPath: '/api/channels/twilio/provision-number'
      preLoaderRoute: typeof ApiChannelsTwilioProvisionNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/businesses/$businessId/status': {
      id: '/api/businesses/$businessId/status'
      path: '/api/businesses/$businessId/status'
      fullPath: '/api/businesses/$businessId/status'
      preLoaderRoute: typeof ApiBusinessesBusinessIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels/twilio/a2p/submit': {
      id: '/api/channels/twilio/a2p/submit'
      path: '/api/channels/twilio/a2p/submit'
      fullPath: '/api/channels/twilio/a2p/submit'
      preLoaderRoute: typeof ApiChannelsTwilioA2pSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface ApiDispatchRouteChildren {
  ApiDispatchDispatchIdApproveRoute: typeof ApiDispatchDispatchIdApproveRoute
  ApiDispatchDispatchIdAssignRoute: typeof ApiDispatchDispatchIdAssignRoute
}

const ApiDispatchRouteChildren: ApiDispatchRouteChildren = {
  ApiDispatchDispatchIdApproveRoute: ApiDispatchDispatchIdApproveRoute,
  ApiDispatchDispatchIdAssignRoute: ApiDispatchDispatchIdAssignRoute,
}

const ApiDispatchRouteWithChildren = ApiDispatchRoute._addFileChildren(
  ApiDispatchRouteChildren,
)

interface ApiJobsRouteChildren {
  ApiJobsJobIdInvoicesRoute: typeof ApiJobsJobIdInvoicesRoute
  ApiJobsJobIdPaymentLinkRoute: typeof ApiJobsJobIdPaymentLinkRoute
  ApiJobsJobIdPaymentsRoute: typeof ApiJobsJobIdPaymentsRoute
  ApiJobsJobIdStatusRoute: typeof ApiJobsJobIdStatusRoute
}

const ApiJobsRouteChildren: ApiJobsRouteChildren = {
  ApiJobsJobIdInvoicesRoute: ApiJobsJobIdInvoicesRoute,
  ApiJobsJobIdPaymentLinkRoute: ApiJobsJobIdPaymentLinkRoute,
  ApiJobsJobIdPaymentsRoute: ApiJobsJobIdPaymentsRoute,
  ApiJobsJobIdStatusRoute: ApiJobsJobIdStatusRoute,
}

const ApiJobsRouteWithChildren =
  ApiJobsRoute._addFileChildren(ApiJobsRouteChildren)

interface ApiMeRouteChildren {
  ApiMeEntitlementsRoute: typeof ApiMeEntitlementsRoute
}

const ApiMeRouteChildren: ApiMeRouteChildren = {
  ApiMeEntitlementsRoute: ApiMeEntitlementsRoute,
}

const ApiMeRouteWithChildren = ApiMeRoute._addFileChildren(ApiMeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallsRoute: CallsRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DispatchRoute: DispatchRoute,
  DownloadAppRoute: DownloadAppRoute,
  InvoicesRoute: InvoicesRoute,
  JobsRoute: JobsRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PortalRoute: PortalRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TeamRoute: TeamRoute,
  WebsiteRoute: WebsiteRoute,
  ApiAuditLogRoute: ApiAuditLogRoute,
  ApiCalendarRoute: ApiCalendarRoute,
  ApiCallsRoute: ApiCallsRoute,
  ApiCustomersRoute: ApiCustomersRoute,
  ApiDispatchRoute: ApiDispatchRouteWithChildren,
  ApiInboxRoute: ApiInboxRoute,
  ApiJobsRoute: ApiJobsRouteWithChildren,
  ApiMeRoute: ApiMeRouteWithChildren,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiOnboardingRoute: ApiOnboardingRoute,
  ApiTeamRoute: ApiTeamRoute,
  ApiBillingCheckoutSessionRoute: ApiBillingCheckoutSessionRoute,
  ApiBillingCustomerPortalRoute: ApiBillingCustomerPortalRoute,
  ApiBillingSubscriptionRoute: ApiBillingSubscriptionRoute,
  ApiConnectOnboardingLinkRoute: ApiConnectOnboardingLinkRoute,
  ApiConnectStatusRoute: ApiConnectStatusRoute,
  ApiMobileSnapshotRoute: ApiMobileSnapshotRoute,
  ApiPaymentsRequestsRoute: ApiPaymentsRequestsRoute,
  ApiSettingsReadinessRoute: ApiSettingsReadinessRoute,
  ApiSignupStartRoute: ApiSignupStartRoute,
  ApiWebhooksStripeConnectRoute: ApiWebhooksStripeConnectRoute,
  ApiWebhooksStripePlatformRoute: ApiWebhooksStripePlatformRoute,
  ApiBusinessesBusinessIdStatusRoute: ApiBusinessesBusinessIdStatusRoute,
  ApiChannelsTwilioProvisionNumberRoute: ApiChannelsTwilioProvisionNumberRoute,
  ApiChannelsTwilioStatusRoute: ApiChannelsTwilioStatusRoute,
  ApiWebhooksTwilioSmsRoute: ApiWebhooksTwilioSmsRoute,
  ApiWebhooksTwilioVoiceRoute: ApiWebhooksTwilioVoiceRoute,
  ApiChannelsTwilioA2pSubmitRoute: ApiChannelsTwilioA2pSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
